name: Run VAI Test Suite

on:
  workflow_dispatch:

jobs:
  run-vai-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Clone Your Fork and Branch
        run: |
          git clone -b brudnak-vai-pagesize https://github.com/brudnak/tests.git
          cd tests
          # Show current branch to confirm
          git branch --show-current
          git log -1 --oneline

      - name: Create config file
        run: |
          # Create the cattle config file
          cat > cattle-config.yaml <<EOF
          rancher:
            host: "${{ secrets.RANCHER_HOST }}"
            adminToken: "${{ secrets.RANCHER_ADMIN_TOKEN }}"
            cleanup: true
            insecure: true
            clusterName: "${{ secrets.CLUSTER_NAME }}"
          EOF

      - name: Install Dependencies
        run: |
          cd tests
          # Install any required dependencies
          go mod download
          go mod tidy

      - name: Run VAI Enabled Test
        env:
          CATTLE_TEST_CONFIG: ${{ github.workspace }}/cattle-config.yaml
        run: |
          cd tests
          # Run the specific test from the test suite
          # Using the exact path and build tags from the test file
          go test -v -timeout 30m \
            -tags="validation,infra.any,cluster.any,extended" \
            ./validation/steve/vai \
            -run TestVaiTestSuite/TestVaiEnabled