name: Run Rancher Webhook Test

on:
  workflow_dispatch:  # Manual trigger for privacy

jobs:
  run-webhook-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'  # Use 1.23 as it seems to be working

      - name: Clone Rancher Tests Repository
        run: |
          git clone https://github.com/rancher/tests.git
          cd tests

      - name: Create config file
        run: |
          # Create the cattle config file
          cat > cattle-config.yaml <<EOF
          rancher:
            host: "${{ secrets.RANCHER_HOST }}"
            adminToken: "${{ secrets.RANCHER_ADMIN_TOKEN }}"
            cleanup: true
            insecure: true
            clusterName: "${{ secrets.CLUSTER_NAME }}"
          EOF

      - name: List available test files
        run: |
          cd tests
          find . -name "*webhook*_test.go" -type f

      - name: Run Webhook Tests with build tags
        env:
          CATTLE_TEST_CONFIG: ${{ github.workspace }}/cattle-config.yaml
        run: |
          cd tests
          # Use the build tags from the test file comment
          go test -v -tags=validation,infra.any,cluster.any,stress ./validation/charts -run TestWebhookTestSuite